### ISSUE TITLE
Month in UI to schedule an interview has an offset of one month

### ISSUE THREAD

**Issue by galloska** [Proyecto-Nutria/proyecto-nutria.github.io#53]
When I try to set an interview and click on the calendar, instead of the current month, next month is being displayed.

Same happens when I move to the next 1st of the month, which changes the month to be 2 months in advance.

![image](https://user-images.githubusercontent.com/6158469/139172197-1bafb973-8567-4919-a748-df61489c9cef.png)

Also, when moving to 1/1/22, no month is being displayed.

**Comment by galloska** [comment]
Also, and just curious, why can I only move one day by day and not make jumps by week?

That is not very user friendly when trying to set interviews per weekly-basis.

**Comment by GoberInfinity** [comment]
Solved in the [last commit](https://github.com/Proyecto-Nutria/proyecto-nutria.github.io/commit/4a7b186de8e3302b5afabed3339311719dda34be). Thanks for opening the issue.
